---
- name: Nginx | Install
  apt: name=nginx state=present update_cache=true

- name: Nginx | Remove default config
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Nginx | Copy vhosts to place
  template: src=vhost.j2 dest=/etc/nginx/sites-enabled/{{ item.name }}.conf
  with_items: balancer_vhosts
  notify: restart nginx

- name: Nginx | Enable init.d
  service: name=nginx state=started enabled=yes
